config/routes.rb
Rails.application.routes.draw do
 # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  get 'welcome/index'

  resources :couplets
  resources :poets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/couplet.rb
class Couplet < ApplicationRecord
  belongs_to :poet
end

app/models/poet.rb
class Poet < ApplicationRecord
	has_many :couplets
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
#  devise :database_authenticatable, :registerable,
#         :recoverable, :rememberable, :validatable,
#         :trackable, :confirmable, :lockable, :timeoutable, 
#         :omniauthable, omniauth_providers: [:facebook]

  # def self.create_from_provider_data(provider_data)
  #   where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
  #     user.email = provider_data.info.email
  #     user.password = Devise.friendly_token[0, 20]
  #     user.skip_confirmation!
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #before_action :authenticate_user!, except: [:index, :show]

  # private
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
# helper_method :current_user
end

app/controllers/couplets_controller.rb
class CoupletsController < ApplicationController
  before_action :set_couplet, only: [:show, :edit, :update, :destroy]

  # GET /couplets
  # GET /couplets.json
  def index
    @couplets = Couplet.all
  end

  # GET /couplets/1
  # GET /couplets/1.json
  def show
  end

  # GET /couplets/new
  def new
    @couplet = Couplet.new
  end

  # GET /couplets/1/edit
  def edit
  end

  # POST /couplets
  # POST /couplets.json
  def create
    @couplet = Couplet.new(couplet_params)

    respond_to do |format|
      if @couplet.save
        format.html { redirect_to @couplet, notice: 'نئے شعر کا کامیابی سے اضافہ کر لیا گیا۔' }
        format.json { render :show, status: :created, location: @couplet }
      else
        format.html { render :new }
        format.json { render json: @couplet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couplets/1
  # PATCH/PUT /couplets/1.json
  def update
    respond_to do |format|
      if @couplet.update(couplet_params)
        format.html { redirect_to @couplet, notice: 'شعر کامیابی سے صحیح کرلیا گیا۔' }
        format.json { render :show, status: :ok, location: @couplet }
      else
        format.html { render :edit }
        format.json { render json: @couplet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couplets/1
  # DELETE /couplets/1.json
  def destroy
    @couplet.destroy
    respond_to do |format|
      format.html { redirect_to couplets_url, notice: 'شعر ریکارڈ سے حذف کرلیا گیا۔' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_couplet
      @couplet = Couplet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def couplet_params
      params.require(:couplet).permit(:couplet, :poet_id)
    end
end

app/controllers/poets_controller.rb
class PoetsController < ApplicationController
   before_action :set_poet,  only: [:show, :edit, :update, :destroy]

  # GET /poets
  # GET /poets.json
  def index
    @poets = Poet.all
  end

  # GET /poets/1
  # GET /poets/1.json
  def show
  end

  # GET /poets/new
  def new
    @poet = Poet.new
  end

  # GET /poets/1/edit
  def edit
  end

  # POST /poets
  # POST /poets.json
  def create
    @poet = Poet.new(poet_params)

    respond_to do |format|
      if @poet.save
        format.html { redirect_to @poet, notice: 'نیا شاعر شامل کر لیا گیا۔' }
        format.json { render :show, status: :created, location: @poet }
      else
        format.html { render :new }
        format.json { render json: @poet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poets/1
  # PATCH/PUT /poets/1.json
  def update
    respond_to do |format|
      if @poet.update(poet_params)
        format.html { redirect_to @poet, notice: 'شاعر کی معلومات کامیابی سے درست کر لی گئی۔' }
        format.json { render :show, status: :ok, location: @poet }
      else
        format.html { render :edit }
        format.json { render json: @poet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poets/1
  # DELETE /poets/1.json
  def destroy
    @poet.destroy
    respond_to do |format|
      format.html { redirect_to poets_url, notice: 'شاعرکا ریکارڈ حذف کر دیا گیا۔' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poet
      @poet = Poet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poet_params
      params.require(:poet).permit(:name, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
		@couplet = Couplet.find_by_id(Couplet.pluck(:id).sample) if Couplet.exists?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couplets_helper.rb
module CoupletsHelper
end

app/helpers/poets_helper.rb
module PoetsHelper
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/couplets/_form.html.erb
<%= form_for(couplet) do |f| %>
  <% if couplet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(couplet.errors.count, "error") %> prohibited this couplet from being saved:</h2>

      <ul>
      <% couplet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :couplet %>
    <%= f.text_area :couplet %>
  </div>

  <div class="field">
    <%= f.label :poet_id %>
    <%= f.collection_select :poet_id, Poet.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/couplets/edit.html.erb
<h1>Editing Couplet</h1>

<%= render 'form', couplet: @couplet %>

<%= link_to 'Show', @couplet %> |
<%= link_to 'Back', couplets_path %>

app/views/couplets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>اشعار</h1>
<%= link_to 'نیا شعر شامل کریں', new_couplet_path %>
<table>
  <thead>
   <!-- <tr>
      <th>Couplet</th>
      <th>Poet</th>
      <th colspan="3"></th>
	 </tr> -->
  </thead>

  <tbody>
    <% @couplets.each do |couplet| %>
      <tr>
        <td><%= simple_format(couplet.couplet) %></td>
        <td><%= couplet.poet.name %></td>

				<%# <td><%= link_to 'Show', couplet %1></td> %> 
        <%# <td><%= link_to 'تصحیح کریں', edit_couplet_path(couplet) %1></td> %>
				<%# <td><%= link_to 'Destroy', couplet, method: :delete, data: { confirm: 'Are you sure?' } %1></td> %> 

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/couplets/new.html.erb
<h1>نیا شعر</h1>

<%= render 'form', couplet: @couplet %>

<%= link_to 'Back', couplets_path %>

app/views/couplets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Couplet:</strong>
  <%= @couplet.couplet %>
</p>

<p>
  <strong>Poet:</strong>
  <%= @couplet.poet.name %>
</p>

<%= link_to 'Edit', edit_couplet_path(@couplet) %> |
<%= link_to 'Back', couplets_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'سخنور', root_path %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'اشعار', couplets_path %>
      </li>
      <li>
        <%= link_to 'شعراء', poets_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl" lang="ur">
  <head>
    <title>سخنور</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', cache: true, 'data-turbolinks-track': 'reload' %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/poets/_form.html.erb
<%= form_for(poet) do |f| %>
  <% if poet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poet.errors.count, "error") %> prohibited this poet from being saved:</h2>

      <ul>
      <% poet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
		add an image.....
		<%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poets/edit.html.erb
<h1>Editing Poet</h1>

<%= render 'form', poet: @poet %>

<%= link_to 'Show', @poet %> |
<%= link_to 'Back', poets_path %>

app/views/poets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>شعراء</h1>

<%= link_to 'نیا شاعر شامل کریں', new_poet_path %>
<br>
<br>

<table>
  <thead>
   <!-- <tr>
      <th>نام</th>
      <th colspan="3"></th>
	 </tr> -->
  </thead>

  <tbody>
    <% @poets.each do |poet| %>
      <tr>
        <td><%= link_to poet.name, poet %></td>
				<td><%= link_to image_tag(poet.image_url(:thumb).to_s), poet %>
        <td><%= link_to "#{poet.name} کے اشعار", poet %></td>

        <%# <td><%= link_to 'تصحیح کریں', edit_poet_path(poet) %1></td> %>
				<%# <td><%= link_to 'Destroy', poet, method: :delete, data: { confirm: 'Are you sure?' } %1></td> %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/poets/new.html.erb
<h1>New Poet</h1>

<%= render 'form', poet: @poet %>

<%= link_to 'Back', poets_path %>

app/views/poets/show.html.erb
<p id="notice"><%= notice %></p>

<%# <p> %>
<%# <strong> <%= @poet.name if Poet.exists? %1> کے اشعار </strong> %>
<%# </p> %>
<%# <p> %>
<%#  <%= image_tag(@poet.image_url.to_s) %1> %>
<%# </p> %>
<%# <% if Poet.exists? %1> %>
<%# <% @poet.couplets.each do |c|  %1> %>
<%# 	<p> <%= simple_format(c.couplet) %1></p> %>
<%# <% end %1> %>
<%# <% end %1> %>
<%#  <%= link_to 'Edit', edit_poet_path(@poet) %1> %> 
<%# <p> %> 
<%# <%= link_to 'تمام شعراء', poets_path %1> %>
<%# </p> %>


<div class="card m-5">

  <div class="card-header">
    <p>
    <strong> <%= @poet.name %> کے اشعار </strong>
    </p>
    <%= image_tag(@poet.image_url.to_s, class: "float-left") %>
  </div>

  <div class="card-body">
    <% @poet.couplets.each do |c|  %>
        <%= simple_format(c.couplet) %>
    <% end %>
  </div>

  <div class="card-footer">
    <%= link_to 'تمام شعراء', poets_path %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron jubmotron-fluid">
  <div class="container">
    <% if Couplet.exists?  %>
      <h1><%= simple_format(@couplet.couplet) %> </h1>
      <p>	<%= Poet.find(@couplet.poet_id).name  %>  </p>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <p>اردو شاعری کی دلچسپ اور بہترین ویب سائٹس</p>
  </div>
  <div class="row">
    <ul>
      <li>
        <a href="https://sukhansara.com/" target="_blank">سخن سرا</a>
      </li>
      <li>
        <a href="http://www.rekhta.org" target="_blank">ریختہ</a>
      </li>
    </ul>
  </div> 
</div>